project:
  type: website
  output-dir: docs
  
website:
  title: "Privacy and Public Policy Conference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - participation.qmd
      # - schedule.qmd
      # - registration.qmd
      # - support.qmd
      - committee.qmd
      - travel.qmd
      - text: Past Conferences
        menu:
          - text: 2024 PPPC
            href: prev_yrs/2024_index.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

